application: woodzu123
version: setup
runtime: php
api_version: 1
#threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$


handlers:
- url: /media
  static_dir: media
  application_readable: true

- url: /images
  static_dir: images
  application_readable: true

- url: /templates/(.*\.(css$|js$|ico$|jpg$|png$|gif$))
  static_files: templates/\1
  upload: templates/(.*\.(css$|js$|ico$|jpg$|png$|gif$))
  application_readable: true

- url: /administrator/templates/(.*\.(css$|js$|ico$|jpg$|png$|gif$))
  static_files: administrator/templates/\1
  upload: administrator/templates/(.*\.(css$|js$|ico$|jpg$|png$|gif$))
  application_readable: true
  secure: always

- url: /installation/template/(.*\.(css$|js$|ico$|jpg$|png$|gif$))
  static_files: installation/template/\1
  upload: installation/template/(.*\.(css$|js$|ico$|jpg$|png$|gif$))
  application_readable: true
  secure: always


- url: /installation/(.+)
  script: installation/\1
  secure: always
  login: admin

- url: /installation/
  script: installation/index.php
  secure: always
  login: admin

- url: /administrator/(.+)
  script: administrator/\1
  secure: always
  login: admin

- url: /administrator/
  script: administrator/index.php
  secure: always
  login: admin

- url: /(.+)?/?
  script: index.php
